#ifdef CPAPDASH_WITH_SEFAM

// End to end over the synthetic cards in tests/fixtures/sefam. They are
// synthetic because no donor card has arrived yet (SDD-005), and they are
// generated by tests/fixtures/sefam/gen/make_fixtures.py with a header length
// and a scrambling key that appear nowhere in the library -- so a parser that
// ever starts assuming either one fails here.

#include <gtest/gtest.h>

#include "cpapdash/parser/ISessionParser.h"
#include "cpapdash/parser/SefamParser.h"

#include <cmath>
#include <filesystem>
#include <string>
#include <vector>

using namespace cpapdash::parser;
namespace fs = std::filesystem;

namespace {

// ctest runs from the build directory, a hand-run ./run_tests usually from the
// repository root, so neither path alone finds the fixtures.
#ifndef CPAPDASH_PARSER_SOURCE_DIR
#define CPAPDASH_PARSER_SOURCE_DIR "."
#endif

std::string fixturePath(const std::string& name) {
    const std::string rel = "tests/fixtures/sefam/" + name;
    for (const std::string& base : {std::string(CPAPDASH_PARSER_SOURCE_DIR) + "/",
                                    std::string(""),
                                    std::string("../"),
                                    std::string("../../")}) {
        std::error_code ec;
        if (fs::exists(base + rel, ec)) return base + rel;
    }
    return {};
}

const char* kCardSession = "card/1263R/24462543/DATA_0";
const char* kCardRoot = "card";

double avgOf(const std::vector<BreathingSummary>& rows,
             std::optional<double> BreathingSummary::*field) {
    double sum = 0;
    int n = 0;
    for (const auto& r : rows) if ((r.*field).has_value()) { sum += *(r.*field); ++n; }
    return n ? sum / n : 0;
}

// The raw flow and pressure stats are plain doubles on BreathingSummary; the
// derived ones are optional.
double avgOf(const std::vector<BreathingSummary>& rows,
             double BreathingSummary::*field) {
    double sum = 0;
    for (const auto& r : rows) sum += r.*field;
    return rows.empty() ? 0 : sum / static_cast<double>(rows.size());
}

} // namespace

// ── Detection ───────────────────────────────────────────────────────────────

TEST(SefamDetect, SessionManifestNamesTheBrand) {
    EXPECT_EQ(detectManufacturer(std::vector<std::string>{"DATA_0.INI"}),
              DeviceManufacturer::SEFAM);
    EXPECT_EQ(detectManufacturer(std::vector<std::string>{
                  "1263R/24462543/DATA_0/DATA_0.INI"}),
              DeviceManufacturer::SEFAM);
    EXPECT_EQ(detectManufacturer(std::vector<std::string>{"data_12/data_12.ini"}),
              DeviceManufacturer::SEFAM);
}

// A bare ".ini" is far too ordinary a name to hand a brand to. What makes the
// Sefam one safe is that the file is named after the folder holding it.
TEST(SefamDetect, AnOrdinaryIniIsNotASefamCard) {
    EXPECT_NE(detectManufacturer(std::vector<std::string>{"settings.ini"}),
              DeviceManufacturer::SEFAM);
    EXPECT_NE(detectManufacturer(std::vector<std::string>{"Report/Report.ini"}),
              DeviceManufacturer::SEFAM);
    EXPECT_NE(detectManufacturer(std::vector<std::string>{"DATA_X.INI"}),
              DeviceManufacturer::SEFAM);
    // Right filename, wrong folder: the pair is the signature.
    EXPECT_NE(detectManufacturer(std::vector<std::string>{"Report/DATA_0.INI"}),
              DeviceManufacturer::SEFAM);
}

TEST(SefamDetect, FoundFromTheCardRootAndFromTheSessionFolder) {
    const auto root = fixturePath(kCardRoot);
    const auto session = fixturePath(kCardSession);
    ASSERT_FALSE(root.empty());
    ASSERT_FALSE(session.empty());

    // The session sits two levels down, under <model>/<serial>/, so unlike every
    // other brand here it cannot be found by looking in one directory.
    EXPECT_EQ(detectManufacturer(root), DeviceManufacturer::SEFAM);
    EXPECT_EQ(detectManufacturer(session), DeviceManufacturer::SEFAM);
}

TEST(SefamDetect, FactoryBuildsTheParser) {
    auto parser = createParser(DeviceManufacturer::SEFAM);
    ASSERT_NE(parser, nullptr);
    EXPECT_EQ(parser->manufacturer(), DeviceManufacturer::SEFAM);
}

// ── A scrambled card ────────────────────────────────────────────────────────

TEST(SefamParse, ScrambledSessionIsReadWithoutBeingToldHow) {
    const auto dir = fixturePath(kCardSession);
    ASSERT_FALSE(dir.empty()) << "run tests/fixtures/sefam/gen/make_fixtures.py";

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-1", "");
    ASSERT_NE(s, nullptr);

    const auto& notes = parser.lastNotes();
    EXPECT_EQ(notes.header_bytes, 101u);
    EXPECT_EQ(notes.descrambler.kind, SefamDescrambler::Kind::SingleByteXor);
    EXPECT_EQ(notes.descrambler.key, 0x9F);
    EXPECT_TRUE(notes.descrambler.confirmed_by_idle_run);

    EXPECT_EQ(s->manufacturer, DeviceManufacturer::SEFAM);
    EXPECT_EQ(s->serial_number, "1263R24462543");
    // The caller passed no name, so the model string out of the INI stands in.
    EXPECT_EQ(s->device_name, "S.Box_AUTO");
}

TEST(SefamParse, DurationComesFromTheSamplesNotTheIni) {
    const auto dir = fixturePath(kCardSession);
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-1", "");
    ASSERT_NE(s, nullptr);

    // The INI declares an eight-hour programmed recording. The channels hold two
    // minutes, and two minutes is the therapy. Believing the declaration would
    // put an eight-hour denominator under every index.
    ASSERT_TRUE(s->duration_seconds.has_value());
    EXPECT_EQ(*s->duration_seconds, 120);
    ASSERT_TRUE(s->session_end.has_value());
    EXPECT_EQ(*s->session_end, *s->session_start + std::chrono::seconds(120));
}

TEST(SefamParse, StartTimeComesFromTheIni) {
    const auto dir = fixturePath(kCardSession);
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-1", "");
    ASSERT_NE(s, nullptr);
    ASSERT_TRUE(s->session_start.has_value());

    const std::time_t t = std::chrono::system_clock::to_time_t(*s->session_start);
    std::tm local{};
#ifdef _WIN32
    localtime_s(&local, &t);
#else
    localtime_r(&t, &local);
#endif
    EXPECT_EQ(local.tm_year + 1900, 2025);
    EXPECT_EQ(local.tm_mon + 1, 12);
    EXPECT_EQ(local.tm_mday, 13);
    EXPECT_EQ(local.tm_hour, 23);
    EXPECT_EQ(local.tm_min, 45);
}

TEST(SefamParse, PressureAndLeakLandInTheirDeclaredUnits) {
    const auto dir = fixturePath(kCardSession);
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-1", "");
    ASSERT_NE(s, nullptr);

    ASSERT_EQ(s->breathing_summary.size(), 2u);  // 120 s, one row a minute
    EXPECT_TRUE(s->has_summary);

    // The fixture holds a pressure code of about 100 on a channel declaring
    // 0..25.5 cmH2O, which is 10 cmH2O, and a leak code of about 20 on a channel
    // declaring 0..153 L/min, which is 12 L/min. Getting either the descrambling
    // or the header offset wrong produces neither.
    EXPECT_NEAR(avgOf(s->breathing_summary, &BreathingSummary::avg_pressure), 10.0, 0.15);
    EXPECT_NEAR(avgOf(s->breathing_summary, &BreathingSummary::therapy_pressure), 10.0, 0.15);
    EXPECT_NEAR(avgOf(s->breathing_summary, &BreathingSummary::leak_rate), 12.0, 0.4);

    // Flow is centred on roughly zero, as breathing is.
    EXPECT_NEAR(avgOf(s->breathing_summary, &BreathingSummary::avg_flow_rate), 0.0, 5.0);
}

TEST(SefamParse, LeakIsAlsoKeptAtTheRateTheMachineWroteIt) {
    const auto dir = fixturePath(kCardSession);
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-1", "");
    ASSERT_NE(s, nullptr);

    // Per-minute means flatten a blow-out inside one minute; the samples do not.
    EXPECT_EQ(s->native_samples.leak.size(), 120u);
}

TEST(SefamParse, DetectionsAreCountedButNotClassified) {
    const auto dir = fixturePath(kCardSession);
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-1", "");
    ASSERT_NE(s, nullptr);

    // Two runs long enough to be events, and a 0.4 s blip that is not.
    ASSERT_EQ(s->events.size(), 2u);
    EXPECT_DOUBLE_EQ(s->events[0].duration_seconds, 20.0);
    EXPECT_DOUBLE_EQ(s->events[1].duration_seconds, 15.0);
    EXPECT_EQ(parser.lastNotes().unknown_event_codes, 2);

    for (const auto& e : s->events) EXPECT_EQ(e.event_type, EventType::OTHER);

    // What a Sefam detection code means is not known, so nothing reaches an
    // index. An AHI of 0 next to two recorded events is the honest reading.
    ASSERT_TRUE(s->metrics.has_value());
    EXPECT_EQ(s->metrics->total_events, 2);
    EXPECT_EQ(s->metrics->other_events, 2);
    EXPECT_EQ(s->metrics->obstructive_apneas, 0);
    EXPECT_EQ(s->metrics->hypopneas, 0);
    EXPECT_DOUBLE_EQ(s->metrics->ahi, 0.0);
}

TEST(SefamParse, StubChannelsProduceNoVitals) {
    const auto dir = fixturePath(kCardSession);
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-1", "");
    ASSERT_NE(s, nullptr);

    // No oximeter on this night: SpO2, heart rate and position are header-only.
    EXPECT_TRUE(s->vitals.empty());
    EXPECT_TRUE(parser.lastNotes().unmapped_channels.empty());
}

// ── An unscrambled card, with oximetry ──────────────────────────────────────

TEST(SefamParse, UnscrambledCardIsLeftAlone) {
    const auto dir = fixturePath("plain/DATA_1");
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-2", "Bedroom");
    ASSERT_NE(s, nullptr);

    EXPECT_EQ(parser.lastNotes().descrambler.kind, SefamDescrambler::Kind::Identity);
    EXPECT_EQ(s->device_name, "Bedroom");
    EXPECT_NEAR(avgOf(s->breathing_summary, &BreathingSummary::avg_pressure), 10.0, 0.15);
}

TEST(SefamParse, OximetryBecomesVitals) {
    const auto dir = fixturePath("plain/DATA_1");
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-2", "Bedroom");
    ASSERT_NE(s, nullptr);

    ASSERT_EQ(s->vitals.size(), 120u);  // 1 Hz over two minutes
    ASSERT_TRUE(s->vitals[0].spo2.has_value());
    ASSERT_TRUE(s->vitals[0].heart_rate.has_value());
    EXPECT_NEAR(*s->vitals[0].spo2, 96.0, 2.5);
    // The channel declares 25..280 bpm, so a code of 35 is 60 bpm.
    EXPECT_NEAR(*s->vitals[0].heart_rate, 60.0, 5.0);
}

// A channel we can read but have nowhere to put, and a file the INI never
// declares, are both reported rather than dropped in silence. A card carrying
// effort belts should say so, even in a release that cannot chart them.
TEST(SefamParse, UnmappedAndUndeclaredChannelsAreReported) {
    const auto dir = fixturePath("plain/DATA_1");
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    auto s = parser.parseSession(dir, "dev-2", "Bedroom");
    ASSERT_NE(s, nullptr);

    const auto& notes = parser.lastNotes();
    ASSERT_EQ(notes.unmapped_channels.size(), 1u);
    EXPECT_EQ(notes.unmapped_channels[0], "THO");
    ASSERT_EQ(notes.undeclared_files.size(), 1u);
    EXPECT_EQ(notes.undeclared_files[0], "Y17");
}

// ── Refusals ────────────────────────────────────────────────────────────────

TEST(SefamParse, ACardWithNothingRecordedIsRefused) {
    const auto dir = fixturePath("stubs/DATA_2");
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    EXPECT_EQ(parser.parseSession(dir, "dev-3", ""), nullptr);
}

// The header length cannot be recovered here: two channels at the same rate
// leave the equation degenerate, and with no stub there is no length to read
// off. A guessed offset would shift every sample in the night and produce
// numbers that look perfectly reasonable, so the session is refused instead.
TEST(SefamParse, AnUnrecoverableHeaderLengthIsRefusedRatherThanGuessed) {
    const auto dir = fixturePath("ambiguous/DATA_3");
    ASSERT_FALSE(dir.empty());

    SefamParser parser;
    EXPECT_EQ(parser.parseSession(dir, "dev-4", ""), nullptr);
}

TEST(SefamParse, AFolderWithNoManifestIsNotASession) {
    SefamParser parser;
    EXPECT_EQ(parser.parseSession(fixturePath("card"), "dev-5", ""), nullptr);
    EXPECT_EQ(parser.parseSession("/no/such/place", "dev-5", ""), nullptr);
}

#endif // CPAPDASH_WITH_SEFAM
